### ISSUE TITLE
Web App

### ISSUE THREAD

**Issue by meghanuyeda11** [vchinn04/130_Project#7]
## Epic
As a user I want a WebApp to be able to interact with match.ai and get my groups. I also want to be able to communicate with my group members and see my groups.

## User Stories
- [x] UI - Group/Team Sidebar #13
- [x] UI - Join Group #14
- [x] UI - Chat Window #15
- [x] UI - Create Group #16
- [x] UI - Group Settings #17
- [x] UI - Generate Team #26
- [x] Join Group #31 
- [x] Chat #30 
- [x] Create Group #29 
- [x] Group Settings #28 
- [x] Generate Team #26 
- [x] Auth Page #11
- [x] Schema Design #19 
- [x] Schema Types #22 
- [x] Integrate DynamoDB #24
